name: Generate Code Stats and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:  # permite rulare manuală

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      
      - name: Install SCC
  run: |
    LATEST_URL=$(curl -s https://api.github.com/repos/boyter/scc/releases/latest \
      | grep "browser_download_url" \
      | grep "linux_amd64.tar.gz" \
      | cut -d '"' -f 4)
    echo "Downloading from: $LATEST_URL"
    curl -LO "$LATEST_URL"
    ARCHIVE_NAME=$(basename "$LATEST_URL")
    tar -xzf "$ARCHIVE_NAME"
    sudo mv scc /usr/local/bin/

      - name: Generate code statistics
        run: |
          mkdir -p site
          scc . > site/stats.txt

      - name: Generate index.html
        run: |
          echo "<html><head><title>Code Stats</title></head><body><h1>Code Statistics</h1><pre>" > site/index.html
          cat site/stats.txt >> site/index.html
          echo "</pre></body></html>" >> site/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
