name: Generate Code Stats and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:  # permite rulare manuală

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      
      - name: Install SCC
  run: |
    LATEST_URL=$(curl -s https://api.github.com/repos/boyter/scc/releases/latest \
      | grep "browser_download_url" \
      | grep "linux_amd64.tar.gz" \
      | cut -d '"' -f 4)
    echo "Downloading from: $LATEST_URL"
    curl -LO "$LATEST_URL"
    ARCHIVE_NAME=$(basename "$LATEST_URL")
    tar -xzf "$ARCHIVE_NAME"
    sudo mv scc /usr/local/bin/

      - name: Generate code statistics
        run: |
          mkdir -p site
          scc . > site/stats.txt

      # înlocuiește pasul anterior cu:
run: |
  cat <<EOF > site/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Code Statistics – GitHub Actions + SCC</title>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code&family=Inter:wght@400;600&display=swap" rel="stylesheet">
  <style>
    body {
      background-color: #111;
      color: #f1f1f1;
      font-family: 'Inter', sans-serif;
      padding: 2rem;
      line-height: 1.6;
    }
    h1 {
      font-weight: 600;
      font-size: 2rem;
      margin-bottom: 1rem;
    }
    pre {
      background-color: #222;
      padding: 1rem;
      border-radius: 5px;
      overflow-x: auto;
      font-family: 'Fira Code', monospace;
      font-size: 0.9rem;
      white-space: pre-wrap;
    }
    .footer {
      margin-top: 3rem;
      font-size: 0.8rem;
      color: #888;
    }
  </style>
</head>
<body>
  <h1>📊 Code Statistics Report</h1>
  <p>This report was automatically generated using <strong>SCC</strong> via GitHub Actions on your latest commit to the <code>main</code> branch.</p>
  <pre>
EOF

  cat site/stats.txt >> site/index.html

  cat <<EOF >> site/index.html
  </pre>
  <div class="footer">
    Generated by <a href="https://github.com/boyter/scc" target="_blank" style="color: #66f;">SCC</a> + <a href="https://github.com/features/actions" target="_blank" style="color: #66f;">GitHub Actions</a> 🚀
  </div>
</body>
</html>
EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
