name: Generate Code Stats Report

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SCC
        run: |
          curl -LO https://github.com/boyter/scc/releases/latest/download/scc-x86_64-unknown-linux.tar.gz
          tar -xvzf scc-x86_64-unknown-linux.tar.gz
          chmod +x scc
          sudo mv scc /usr/local/bin/scc

      - name: Generate report
        run: |
          mkdir -p site
          scc --format=html --output=site/index.html .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
